import = ["~/.config/alacritty/color-schemes/astrology_vibrant_stellar.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.9
blur = true

[font]
size = 11
normal = { family = "FiraCode Nerd Font", style = "Medium" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }

[cursor]
style = { shape = "Underline", blinking = "Always" }
vi_mode_style = { shape = "Underline", blinking = "Always" }

[mouse]
hide_when_typing = true
