import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.cache/wal/colors-alacritty.toml"
]
[env]
TERM = "xterm-256color"
# WINDOW
[window]
padding = {x = 0, y = 0}
dynamic_padding = true
opacity = 0.9
blur = true
# FONT
[font]
size = 11
normal = {family = "MesloLGM Nerd Font Mono", style = "Regular"}
italic = {family = "MesloLGM Nerd Font Mono", style = "Italic"}
bold = {family = "MesloLGM Nerd Font Mono", style = "Bold"}
