#################
### AUTOSTART ###
#################



# Autostart necessary processes (like notifications daemons, status bars, etc.)
exec-once = fcitx5

# exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprctl setcursor phinger-cursors-light 24
exec-once = udiskie -a
exec-once = hypridle
exec-once = jamesdsp --tray
exec-once = kdeconnect-indicator
exec-once = /home/tiamatt/.config/hypr/scripts/touchpad-status.sh
exec = hyprpaper
exec = env GDK_BACKEND=wayland swaync

# cliphist - clipboard manager
# exec-once = wl-paste --type text --watch cliphist store
# exec-once = wl-paste --type image --watch cliphist store
# exec-once = cliphist wipe & rm .cache/cliphist/db
exec-once = clipse -listen
exec-once = easyeffects --gapplication-service

# Battery state watcher
exec-once = ~/.config/hypr/scripts/battery_state_watcher.sh

# Dashboard
exec-once = ~/.config/hypr/scripts/restore_last_session.sh