#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
exec-once = fcitx5
# exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprctl setcursor phinger-cursors-light 24
exec-once = udiskie -a
exec-once = hypridle

exec = /home/tiamatt/.config/hypr/scripts/touchpad-status.sh
exec = fnott & hyprpaper
# cliphist - clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = easyeffects --gapplication-service
exec-once = cliphist wipe & rm .cache/cliphist/db

#scripts
exec-once = hyprctl dispatch exec $HOME/.config/hypr/scripts/refreshrate_switch.sh
