[colors.primary]
background = "#191724"
foreground = "#E0DEF4"

[colors.normal]
black = "#191724"
red = "#EBCEB3"
green = "#9CCFD8"
yellow = "#F6C177"
blue = "#31748F"
magenta = "#C4A7E7"
cyan = "#EBBCBA"
white = "#E0DEF4"

[colors.bright]
black = "#869C97"
red = "#EB6F92"
green = "#0C3A64"
yellow = "#B2F7A2"
blue = "#FFFFFF"
magenta = "#C4A7E7"
cyan = "#FFFFFF"
white = "#E0DEF4"
