##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# windowrulev1
windowrule = float, class:blueman-manager

windowrule = float, class:org.pulseaudio.pavucontrol
windowrule = size 600 400, class:org.pulseaudio.pavucontrol

windowrule = float, class:nwg-look
windowrule = size 1000 650, class:nwg-look

# windowrule
windowrule = float, class:Thunar
windowrule = size 1200 750, class:Thunar

windowrule = float, class:thunar
windowrule = size 1200 750, class:thunar

windowrule = float, class:org.kde.dolphin
windowrule = size 1200 750, class:org.kde.dolphin

windowrule = float, class:org.gnome.Nautilus
windowrule = size 1200 750, class:org.gnome.Nautilus

windowrule = float, initialClass:nemo
windowrule = size 1200 750, initialClass:nemo

windowrule = float, class:firefox,title:Picture-in-Picture
windowrule = size 800 450, class:firefox,title:Picture-in-Picture

windowrule = size 800 600, title:iwgtk
windowrule = float, title:iwgtk

windowrule = float, class:com.saivert.pwvucontrol
windowrule = size 1200 650, class:com.saivert.pwvucontrol

windowrule = float, class:iwdgui
windowrule = size 700 650, class:iwdgui

# layerrule = blur, waybar

windowrule = suppressevent maximize, class:.* # You'll probably like this
windowrule = noblur,class:^()$,title:^()$
