require("config.lazy")
require("config.keymap")
vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")

-- local builtin = require('telescope.builtin')
vim.cmd("set relativenumber")
vim.cmd("colorscheme tokyonight-night")
-- vim.cmd("colorscheme poimandres")
