[colors.primary]
background = "#{background.strip}"
foreground = "#{foreground.strip}"
dim_foreground = "#7f849c"
bright_foreground = "#{foreground.strip}"

[colors.cursor]
text = "#{background.strip}"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#{background.strip}"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#{background.strip}"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#{background.strip}"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#{background.strip}"
background = "#a6adc8"

[colors.hints.start]
foreground = "#{background.strip}"
background = "#f9e2af"

[colors.hints.end]
foreground = "#{background.strip}"
background = "#a6adc8"

[colors.selection]
text = "#{background.strip}"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#BF616A"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#5e81ac"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#BF616A"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#5e81ac"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#BF616A"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#5e81ac"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
