# -*- conf -*-

# For documentation on these options, see `man fnott.ini`

# Global values
# output=
min-width=0
max-width=500
max-height=0
stacking-order=bottom-up
anchor=top-right
edge-margin-vertical=10
edge-margin-horizontal=10
notification-margin=10
icon-theme=Tela-circle-blue
max-icon-size=32
selection-helper=fuzzel --dmenu -i -p
selection-helper-uses-null-separator=no
play-sound=pw-play message.oga

# Default values, may be overridden in 'urgency' specific sections
layer=top
background=000000ff

border-color=909090ff
border-radius=8
border-size=0

padding-vertical=15
padding-horizontal=20

dpi-aware=no

title-font=JetBrains Mono Nerd Font:size=12
title-color=ffffffff
title-format=<i>%a%A</i>

summary-font=JetBrains Mono Nerd Font:size=10
summary-color=ffffffff
summary-format=<b>%s</b>\n

body-font=JetBrains Mono Nerd Font:size=10
body-color=ffffffff
body-format=%b

progress-bar-height=20
progress-bar-color=ffffffff

sound-file=
icon=

# Timeout values are in seconds. 0 to disable
max-timeout=15
default-timeout=5
idle-timeout=0

[low]

[normal]

[critical]
