################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,preferred,0x0,1.2, bitdepth, 10, cm, srgb
monitor=DP-1,1920x1080@60,-1920x-150,1, bitdepth, 10, cm, srgb

# fallback for new/unconfigured Monitors
monitor= ,preferred, auto, 1, mirror, eDP-1
